<HTML>
<?php
/**********************************************************************
 * $Id: world.phtml,v 1.0 2006/03/01 rroca Exp $
 **********************************************************************
 * based on gmap75 demo from DM Solutions Group
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 **********************************************************************/


/***********************************************************

All this contributed software -guifimaps- should be 
considered under the GNU/GPL Licensing, with the extension
that can only be used for free networks under the Comuns 
Sensefils license (http://guifi.net/ComunsSensefils).

If that's not the case, you are not granted to copy or use 
the contributed software of guifimaps and you should ask
for permission.

************************************************************/


/************************************************************************/
/*        guifimaps mapping engine (PHP/MapScript version)            */
/*                                                                      */
/*      This application uses the PHP/MapScript MapServer extension     */
/*      to navigate through a network.                                  */
/*                                                                      */
/*      See Also:                                                       */
/*        http://mapserver.gis.umn.edu/                                 */
/*        http://www.maptools.org/php_mapscript/                        */
/*        http://www.maptools.org/rosa/                                 */
/*        http://www.mapsherpa.com/gmap/gmap75.phtml                    */
/************************************************************************/

/* -------------------------------------------------------------------- */
/*      Load required modules                                           */
/* -------------------------------------------------------------------- */
if (PHP_OS == "WINNT" || PHP_OS == "WIN32")
    $dlext = "dll";
else
    $dlext = "so";

if (!extension_loaded("MapScript"))
{
    dl("php_mapscript.$dlext");
}
if (!extension_loaded("dbase"))
{
    dl("php_dbase.$dlext");
}


/* -------------------------------------------------------------------- */
/*      Check if maps should be refreshed and do it if yes              */
/* -------------------------------------------------------------------- */
/*if (file_exists('/tmp/ms_tmp/REBUILD')) {
  unlink('/tmp/ms_tmp/REBUILD');
  exec('/home1/fgs/www/htdocs/data/refresh.sh');
}*/ 

$gszCommand = $HTTP_FORM_VARS["CMD"];
if ( sizeof($gszCommand) == 0)
{
    $gszCommand = "ZOOM_IN";
}

include("config.inc.php");
include("world.inc.php");
include("xmlparser.php");

$gLang = $HTTP_FORM_VARS["Lang"];
if ( sizeof($gLang) == 0)
{
    $gLang = 'ca';
}
include("./lang/".$gLang.".php");

if ($HTTP_FORM_VARS["REGION_ID"]) {
  $HTTP_FORM_VARS['ViewRegion'] = set_region($HTTP_FORM_VARS["REGION_ID"]);
  $HTTP_FORM_VARS['Layers'] = 'all';
}

if ($HTTP_FORM_VARS['Layers'] == 'all') {
   $HTTP_FORM_VARS['local_maps'] = 'Y';
   $HTTP_FORM_VARS['Supernodes'] = 'Y';
   $HTTP_FORM_VARS['NodesAP'] = 'Y';
   $HTTP_FORM_VARS['NodesClient'] = 'Y';
   $HTTP_FORM_VARS['NodesProjected'] = 'Y';
   $HTTP_FORM_VARS['LinksWDS'] = 'Y';
   $HTTP_FORM_VARS['LinksClient'] = 'Y';
   $HTTP_FORM_VARS['LinksOffline'] = 'Y';
   $HTTP_FORM_VARS['Tunels'] = 'Y';
   $HTTP_FORM_VARS['Pointer'] = 'Y';
}


if ($HTTP_FORM_VARS["MAP_NAME"])
    $gpoMap = ms_newMapObj(strval($HTTP_FORM_VARS["MAP_NAME"]));
else
   $gpoMap = ms_newMapObj("world.map");

$gszCommand = $HTTP_FORM_VARS["CMD"];
if ((isset($HTTP_FORM_VARS['Lat'])) && (isset($HTTP_FORM_VARS['Lat']))) {
    $HTTP_FORM_VARS['Layers'] = 'all';
    gotoLatLon($HTTP_FORM_VARS['Lat'],$HTTP_FORM_VARS['Lon'],$HTTP_FORM_VARS['Scale']);
}



/* -------------------------------------------------------------------- */
/*      extents set in the .map file.                                   */
/*                                                                      */
/*      max extents are 10% of the map.                                 */
/* -------------------------------------------------------------------- */
$dfTmpDeltaX = ($gpoMap->extent->maxx - $gpoMap->extent->minx)/10;
$dfTmpDeltaY = ($gpoMap->extent->maxy - $gpoMap->extent->miny)/10;
// For now, we disable the 10% buffer until we get new data
$dfTmpDeltaX = 0;
$dfTmpDeltaY = 0;

$dfMapExtMinX = $gpoMap->extent->minx;
$dfMapExtMinY = $gpoMap->extent->miny;
$dfMapExtMaxX = $gpoMap->extent->maxx;
$dfMapExtMaxY = $gpoMap->extent->maxy;

$dfMaxExtMinX = $gpoMap->extent->minx - $dfTmpDeltaX;
$dfMaxExtMinY = $gpoMap->extent->miny - $dfTmpDeltaY;
$dfMaxExtMaxX = $gpoMap->extent->maxx + $dfTmpDeltaX;
$dfMaxExtMaxY = $gpoMap->extent->maxy + $dfTmpDeltaY;

$gInfo = "";


GMap75CheckClick();

$gszCommand = $HTTP_FORM_VARS["CMD"];
if ( sizeof($gszCommand) == 0)
{
    $gszCommand = "ZOOM_IN";
}


include_once("localmaps.inc.php");

/* -------------------------------------------------------------------- */
/*      swich between the rosa java applet and simple html for          */
/*      zooming and querying.                                           */
/* -------------------------------------------------------------------- */

if (strlen($HTTP_FORM_VARS["PREVIOUS_MODE"])==0)
    $gbIsHtmlMode = 1;  // Start with Java On by default
else
    $gbIsHtmlMode = intval($HTTP_FORM_VARS["PREVIOUS_MODE"]);

if ($HTTP_FORM_VARS[JavaOn_x])
  $gbIsHtmlMode = 0;

if ($HTTP_FORM_VARS[JavaOff_x])
  $gbIsHtmlMode = 1;

function IsHtmlMode()
{
    GLOBAL $gbIsHtmlMode;
    return $gbIsHtmlMode;
}


if ($HTTP_FORM_VARS['IFRAME'] == 'Y') {
  print '<HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=UTF-8"></HEAD><HTML><FORM METHOD=GET NAME="myform">';
  print '<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0"><TR><TD>';
  
  // deactivate key & scale
  $gpoMap->reference->set('status',0);
  $gpoMap->scalebar->set('status',0);
  GMapDrawMap();
  print '</TD><TD>';

  print '<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">';
  print '<TR><TD><INPUT TYPE="radio" NAME="CMD" VALUE="ZOOM_IN" ';
  if ($gszCommand == "ZOOM_IN") echo "CHECKED";
  print '>';
  print '</TD><TD><IMG SRC="images/icon_zoomin.gif" WIDTH="25" HEIGHT="25"></TD></TR>';
  print '<TR><TD><INPUT TYPE="radio" NAME="CMD" VALUE="ZOOM_OUT" ';
  if ($gszCommand == "ZOOM_OUT") echo "CHECKED";
  print '>';
  print '</TD><TD><IMG SRC="images/icon_zoomout.gif" WIDTH="25" HEIGHT="25"></TD></TR>';
  print '<TR><TD><INPUT TYPE="radio" NAME="CMD" VALUE="RECENTER" ';
  if ($gszCommand == "RECENTER") echo "CHECKED";
  print '>';
  print '</TD><TD><IMG SRC="images/icon_recentre.gif" WIDTH="25" HEIGHT="25"></TD></TR>';
  print '</TABLE>';

  print '</TD></TR>';
  $add = addNode();
  if ($add != null)
    print '<TR><TD><CENTER>'.$add.'</CENTER></TD></TR>';
  print '</TABLE>';
  print '<INPUT TYPE=HIDDEN NAME=Layers VALUE="all">';
  print '<INPUT TYPE=HIDDEN NAME=IFRAME VALUE="Y">';
  if ($HTTP_FORM_VARS['MapSize'])
    print '<INPUT TYPE=HIDDEN NAME=MapSize VALUE="'.$HTTP_FORM_VARS['MapSize'].'">';
  else
    print '<INPUT TYPE=HIDDEN NAME=MapSize VALUE="400,300">';
  print '</FORM></HTML>';
  exit(0);
}

?>

<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; CHARSET=UTF-8">

<SCRIPT LANGUAGE="JavaScript">

function ProvinceSelected()
{
    if (document.forms[0].ViewRegion.selectedIndex != 0 &&
        document.forms[0].ViewRegion.selectedIndex !=1)
    document.forms[0].submit();
}
function LangSelected()
{
    if (document.forms[0].Lang.selectedIndex != 0 &&
        document.forms[0].Lang.selectedIndex !=1)
    document.forms[0].submit();
}
function MapSizeSelected()
{
    if (document.forms[0].MapSize.selectedIndex != 0 &&
        document.forms[0].MapSize.selectedIndex !=1)
    document.forms[0].submit();
}
</SCRIPT>


<TITLE>guifi.net World Maps</TITLE>
</HEAD>

<BODY BGCOLOR="#FFFFFF">
<!-- <?php echo ms_getVersion(); ?> -->
<FORM METHOD=GET NAME="myform">
  <TABLE BORDER="0" CELLSPACING="5" CELLPADDING="0">
    <TR>
      <TD VALIGN="TOP" ALIGN="CENTER">

        <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
          <TR>
            <TD><IMG SRC="images/corner_TL_LB.jpg" WIDTH="4" HEIGHT="4"></TD>
            <TD BGCOLOR="#f87046"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD><IMG SRC="images/corner_TR_LB.jpg" WIDTH="4" HEIGHT="4"></TD>
          </TR>
          <TR ALIGN="CENTER">
            <TD BGCOLOR="#f87046">&nbsp;</TD>
            <TD BGCOLOR="#f87046"><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2" COLOR="white"><B><?php echo $text['Legend'] ?></B></FONT></TD>
            <TD BGCOLOR="#f87046">&nbsp;</TD>
          </TR>
           <TR>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
           </TR>
            <TR>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
          </TR>
          <TR>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
            <TD BGCOLOR="#fb470c">
              <TABLE WIDTH="100%" BORDER="0" CELLSPACING="1" CELLPADDING="2">
                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER"><IMG SRC="images/icon_eye.gif" WIDTH="17" HEIGHT="11"></TD>
                  <TD ALIGN="CENTER">&nbsp;</TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><B><?php echo $text['Layer'] ?></B></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="Pointer" VALUE="Y"
        <?php if (GMapGetStatus("Pointer") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_pointer.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['Marker'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="local_maps" VALUE="Y"
        <?php if (GMapGetStatus("BaseMap") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_drain.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['BackgroundMap'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD COLSPAN="3" ALIGN="center"><FONT FACE="Arial, Helvetica, sans-serif" SIZE="1"><?php echo $text['Nodes'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="Supernodes" VALUE="Y"
         <?php if (GMapGetStatus("Supernodes") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_supernode.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['Supernode'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="NodesAP" VALUE="Y"
         <?php if (GMapGetStatus("NodesAP") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_nodeaponline.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['AP'] ?></FONT></TD>
                </TR> 

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="NodesClient" VALUE="Y"
         <?php if (GMapGetStatus("NodesClient") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_nodeclientonline.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['Client'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="NodesProjected" VALUE="Y"
         <?php if (GMapGetStatus("NodesProjected") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_nodeprojectat.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['Planned'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD COLSPAN="3" ALIGN="center"><FONT FACE="Arial, Helvetica, sans-serif" SIZE="1"><?php echo $text['Links'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="LinksWDS" VALUE="Y"
       <?php if (GMapGetStatus("LinksWDS") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_linkwds.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['WDS'] ?></FONT></TD>
                </TR>
                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="LinksClient" VALUE="Y"
       <?php if (GMapGetStatus("LinksClient") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_linkclient.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['Client'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE="checkbox" NAME="LinksOffline" VALUE="Y"
        <?php if (GMapGetStatus("LinksOffline") == 1) echo "CHECKED"; ?>>
                  </TD>
                  <TD ALIGN="CENTER"><IMG SRC="images/leg_linkprojected.gif" WIDTH="20" HEIGHT="15"></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['Planned'] ?></FONT></TD>
                </TR>

                <TR BGCOLOR="#FFFFFF">
                </TR>

                <TR BGCOLOR="#FFFFFF">
                  <TD ALIGN="CENTER">
                    <INPUT TYPE=IMAGE SRC="images/icon_redraw.gif" WIDTH="19" HEIGHT="19" NAME=redraw BORDER=0>
                  </TD>
                  <TD COLSPAN="2"><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php echo $text['Redraw'] ?></FONT></TD>
                </TR>
              </TABLE>
            </TD>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
          </TR>
            <TR>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
          </TR>
           <TR>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
           </TR>
            <TR>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
          </TR>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
            <TD BGCOLOR="#fb470c" ALIGN="LEFT">
              <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2">
              <SELECT NAME="Lang"  onChange="LangSelected()">
                <OPTION><?php echo $text['Language'] ?></OPTION>
                <OPTION>- - - - - - - - - - - - - - -</OPTION>
                <?php language_select($gLang) ?>
              </SELECT >
            </TD>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
          <TR>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
            <TD BGCOLOR="#fb470c" ALIGN="LEFT">
              <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2">
              <SELECT NAME="ViewRegion"  onChange="ProvinceSelected()">
                <OPTION><?php echo $text['ViewDirectly'] ?></OPTION>
                <OPTION>- - - - - - - - - - - - - - -</OPTION>
                <?php regions_select() ?>
              </SELECT >

              </FONT>
            </TD>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
          </TR>
          <TR>
            <TD><IMG SRC="images/corner_BL_DB.jpg" WIDTH="4" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD><IMG SRC="images/corner_BR_DB.jpg" WIDTH="4" HEIGHT="4"></TD>
          </TR>

        </TABLE>

      </TD>
      <TD VALIGN=TOP ALIGN="RIGHT">
        <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
          <TR>
            <TD><IMG SRC="images/corner_TL_LB.jpg" WIDTH="4" HEIGHT="4"></TD>
            <TD BGCOLOR="#f87046"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD><IMG SRC="images/corner_TR_LB.jpg" WIDTH="4" HEIGHT="4"></TD>
          </TR>
          <TR ALIGN="CENTER">
            <TD BGCOLOR="#f87046">&nbsp;</TD>
            <TD BGCOLOR="#f87046"><FONT COLOR="white" FACE="Arial, Helvetica, sans-serif" SIZE="2"><B>guifi.net World Maps</B></FONT></TD>
            <TD BGCOLOR="#f87046">&nbsp;</TD>
          </TR>
           <TR>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
           </TR>
          <TR>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
          </TR>
          <TR>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
            <TD BGCOLOR="#999999">
              <TABLE WIDTH="400" BORDER="0" CELLSPACING="1" CELLPADDING="0" HEIGHT="300">
                <TR BGCOLOR="FFFFFF" ALIGN="CENTER">
                  <TD><?php GMapDrawMap() ?></TD>
                </TR>
              </TABLE>
            </TD>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
          </TR>
          <TR>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
            <TD BGCOLOR="#FFFFFF" ALIGN="CENTER"><?php GMapDrawScaleBar() ?></TD>  
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
          </TR>
          <TR>
            <TD><IMG SRC="images/corner_BL_DB.jpg" WIDTH="4" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD><IMG SRC="images/corner_BR_DB.jpg" WIDTH="4" HEIGHT="4"></TD>
          </TR>
        </TABLE>

        </TD>
        <TD VALIGN="TOP">

        <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
          <TR>
            <TD><IMG SRC="images/corner_TL_LB.jpg" WIDTH="4" HEIGHT="4"></TD>
            <TD BGCOLOR="#f87046"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD><IMG SRC="images/corner_TR_LB.jpg" WIDTH="4" HEIGHT="4"></TD>
          </TR>
          <TR ALIGN="CENTER">
            <TD BGCOLOR="#f87046">&nbsp;</TD>
            <TD BGCOLOR="#f87046"><FONT COLOR="white" FACE="Arial, Helvetica, sans-serif" SIZE="2"><B><?php echo $text['Reference'] ?></B></FONT></TD>
            <TD BGCOLOR="#f87046">&nbsp;</TD>
          </TR>
           <TR>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
           </TR>
            <TR>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
          </TR>
          <TR>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
            <TD><?php GMapDrawKeyMap() ?></TD>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
          </TR>
          <TR>
            <TD><IMG SRC="images/corner_BL_DB.jpg" WIDTH="4" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD><IMG SRC="images/corner_BR_DB.jpg" WIDTH="4" HEIGHT="4"></TD>
          </TR>
        </TABLE>


        <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2">
        <BR>
        <SELECT NAME="MapSize" onChange="MapSizeSelected()">

          <OPTION><?php echo $text['MapSize'] ?></OPTION>

          <OPTION>---------------</OPTION>

          <OPTION VALUE="400,300"
                <?php if (($gpoMap->width == 400) && ($gpoMap->height == 300))
                 echo "SELECTED";?>> 400 x 300</OPTION>

          <OPTION VALUE="600,450"
                 <?php if (($gpoMap->width == 600) && ($gpoMap->height == 450))
                 echo "SELECTED";?>> 600 x 450</OPTION>

          <OPTION VALUE="800,600"
                 <?php if (($gpoMap->width == 800) && ($gpoMap->height == 600))
                 echo "SELECTED";?>> 800 x 600</OPTION>

        </SELECT>
        </FONT><BR>
        <BR>


  <?php if (!IsHtmlMode()) echo "<!--" ?>
        <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">

          <TR>

            <TD>

              <INPUT TYPE="radio" NAME="CMD" VALUE="ZOOM_IN"
         <?php if ($gszCommand == "ZOOM_IN") echo "CHECKED"; ?> >
    </TD>
            <TD><IMG SRC="images/icon_zoomin.gif" WIDTH="25" HEIGHT="25"></TD>
          </TR>

          <TR>

            <TD>

              <INPUT TYPE="radio" NAME="CMD" VALUE="ZOOM_OUT"
        <?php if ($gszCommand == "ZOOM_OUT") echo "CHECKED"; ?> >
    </TD>
            <TD><IMG SRC="images/icon_zoomout.gif" WIDTH="25" HEIGHT="25"></TD>
          </TR>

          <TR>

            <TD>

              <INPUT TYPE="radio" NAME="CMD" VALUE="RECENTER"
             <?php if ($gszCommand == "RECENTER") echo "CHECKED"; ?> >
    </TD>
            <TD><IMG SRC="images/icon_recentre.gif" WIDTH="25" HEIGHT="25"></TD>
          </TR>

          <TR>

            <TD>

              <INPUT TYPE="radio" NAME="CMD" VALUE="QUERY_POINT"
               <?php if ($gszCommand == "QUERY_POINT") echo "CHECKED"; ?>>
    </TD>
            <TD><IMG SRC="images/icon_info.gif" WIDTH="25" HEIGHT="25"></TD>
          </TR>

        </TABLE>
        <TABLE>

          <TR>
            <TD>
               <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2">
	       <?php echo $text['License'] ?>
               </FONT>
            </TD>
          </TR>
          <TR>
            <TD><A HREF="http://guifi.net/ComunsSensefils"><IMG BORDER="0" SRC="http://guifi.net/files/csf.gif"></A></TD>
          </TR>
        </TABLE>
        <?php if (!IsHtmlMode()) echo "-->" ?>
        <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2">

        </FONT></TD>
    </TR>
    <TR>
      <TD VALIGN="TOP" ALIGN="CENTER">
        <TABLE CELLPADDING="2" CELLSPACING="0">
          <TR>
            <TD><INPUT TYPE="image" BORDER="0"  <?php if (IsHtmlMode()) printf("NAME=\"JavaOn\" SRC=\"images/java_on.gif\""); else printf("NAME=\"JavaOff\" SRC=\"images/java_off.gif\"");?> WIDTH="24" HEIGHT="25"></TD>
            <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><?php if (IsHtmlMode()) printf($text['JavaOFF']); else printf($text['JavaON']);?></FONT>
            <INPUT TYPE=HIDDEN NAME=PREVIOUS_MODE VALUE=<?php echo IsHtmlMode(); ?>></TD>
          </TR>
        </TABLE>
      </TD>
      <TD ALIGN="CENTER">

        <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
          <TR>
            <TD><IMG SRC="images/corner_TL_LB.jpg" WIDTH="4" HEIGHT="4"></TD>
            <TD BGCOLOR="#f87046"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD><IMG SRC="images/corner_TR_LB.jpg" WIDTH="4" HEIGHT="4"></TD>
          </TR>
          <TR ALIGN="CENTER">
            <TD BGCOLOR="#f87046">&nbsp;</TD>
                    <TD BGCOLOR="#f87046"><FONT COLOR="white" FACE="Arial, Helvetica, sans-serif" SIZE="2"><B><?php echo $text['Information'] ?></B></FONT></TD>
            <TD BGCOLOR="#f87046">&nbsp;</TD>
          </TR>
           <TR>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
             <TD BGCOLOR="#999999"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="1"></TD>
           </TR>
            <TR>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
          </TR>
          <TR>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
            <TD WIDTH=<?php echo $gpoMap->width; ?>><FONT FACE="Arial, Helvetica, sans-serif" SIZE="0.8"><?php GMapDumpQueryResults(); ?></FONT></TD>
            <TD BGCOLOR="#fb470c">&nbsp;</TD>
          </TR>
          <TR>
            <TD><IMG SRC="images/corner_BL_DB.jpg" WIDTH="4" HEIGHT="4"></TD>
            <TD BGCOLOR="#fb470c"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="4"></TD>
            <TD><IMG SRC="images/corner_BR_DB.jpg" WIDTH="4" HEIGHT="4"></TD>
          </TR>
        </TABLE>

      </TD>
    </TR>
    <TR>
      <TD COLSPAN="3">&nbsp;</TD>
    </TR>
    <TR>
      <TD COLSPAN="3" BGCOLOR="#E2EFF5"><IMG SRC="images/pixel.gif" WIDTH="1" HEIGHT="2"></TD>
    </TR>
    <TR>
      <TD COLSPAN="3">&nbsp;</TD>
    </TR>
    <TR>
      <TD COLSPAN="3">
        <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
          <TR ALIGN="CENTER">
            <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><A HREF="http://guifi.net"><IMG SRC="images/logo_guifi.png" WIDTH="181" HEIGHT="52" BORDER="0"></A></FONT></TD>
            <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><A HREF="http://mapserver.gis.umn.edu/"><IMG SRC="images/powered_mapserver.jpg" WIDTH="96" HEIGHT="58" BORDER="0"></A></FONT></TD>
            <TD>
              <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
                <TR>
                  <TD><A HREF="http://php.net"><IMG SRC="images/logo_php.gif" WIDTH="34" HEIGHT="19" BORDER="0"></A></TD>
                  <TD><FONT FACE="Arial, Helvetica, sans-serif" SIZE="2">/ <A HREF="http://www.maptools.org/php_mapscript/">MapScript</A></FONT></TD>
                </TR>
              </TABLE>
            </TD>
            <TD>
                <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><A HREF="http://www.maptools.org/rosa/"><IMG SRC="images/powered_rosa.jpg" WIDTH="100" HEIGHT="36" BORDER="0"></A></FONT></TD>
              <!-- <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><A HREF="http://www.nasa.gov/"><IMG SRC="images/Logo_NASA.jpg" WIDTH="64" HEIGHT="57" BORDER="0"></A></FONT>
                </TD><TD>
              <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><A HREF="http://www.unesco.org/"><IMG SRC="images/unesco_logo_en.gif" BORDER="0"></A></FONT>
                </TD>-->
              <TD>
              <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><A HREF="http://www.geoportal-idec.net/"><IMG SRC="images/logoidec.gif" BORDER="0"></A></FONT>
                </TD><TD>
              <FONT FACE="Arial, Helvetica, sans-serif" SIZE="2"><A HREF="http://www.idee.es/"><IMG SRC="images/Logo_IDEE.gif" BORDER="0"></A></FONT>
            </TD></TR>
          </TR>
        </TABLE>
      </TD>
    </TR>

  </TABLE>
      <?php if ($HTTP_FORM_VARS["MAP_NAME"])
        printf("<INPUT TYPE=HIDDEN NAME=MAP_NAME VALUE=\"%s\">",strval($HTTP_FORM_VARS["MAP_NAME"])); ?>
</FORM>
</BODY>
</HTML>



                                                                                                                               


